# Generated by Django 4.2.1 on 2023-10-07 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("room", "0003_hashtag_message_image_message_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="joined_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
