# Generated by Django 4.2.1 on 2023-10-07 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("room", "0004_room_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="user",
        ),
        migrations.AddField(
            model_name="room",
            name="user",
            field=models.ManyToManyField(
                null=True, related_name="joined_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
