# Generated by Django 4.2.1 on 2023-10-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0005_remove_room_user_room_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="user",
            new_name="users",
        ),
    ]
