# Generated by Django 4.2.1 on 2023-11-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0007_alter_room_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_img",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
