# Generated by Django 4.2.1 on 2023-11-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0008_room_room_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
