# Generated by Django 4.2.1 on 2024-02-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0010_room_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="hashtags",
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name="Hashtag",
        ),
    ]
