# Generated by Django 4.2.1 on 2024-02-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0014_alter_room_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="created_by",
        ),
    ]
