# Generated by Django 4.2.1 on 2024-04-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0016_room_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
