# Generated by Django 4.2.3 on 2023-09-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_customuser_delete_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
