# Generated by Django 4.2.3 on 2023-09-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_customuser_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
