# Generated by Django 4.2.3 on 2023-09-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
