# Generated by Django 4.2.1 on 2023-09-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_trendingmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trendingmessage",
            options={"ordering": ("date_added",)},
        ),
        migrations.AddField(
            model_name="trendingmessage",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
