# Generated by Django 4.2.1 on 2023-09-16 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_trendingmessage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendingmessage",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="main.trendingmessage",
            ),
        ),
    ]
