# Generated by Django 4.2.1 on 2023-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_trendingmessage_parent_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="trendingmessage",
            name="hashtags",
            field=models.ManyToManyField(to="main.hashtag"),
        ),
    ]
