# Generated by Django 4.2.1 on 2023-09-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_hashtag_trendingmessage_hashtags"),
    ]

    operations = [
        migrations.AddField(
            model_name="hashtag",
            name="count",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
