# Generated by Django 4.2.1 on 2023-09-21 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_hashtag_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hashtag",
            options={"ordering": ("-count",)},
        ),
    ]
