# Generated by Django 4.2.1 on 2023-10-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_trendingmessage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendingmessage",
            name="likes",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
