# Generated by Django 4.2.1 on 2023-10-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_trendingmessage_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trendingmessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
