# Generated by Django 4.2.1 on 2023-10-08 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0023_alter_trendingmessage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendingmessage",
            name="userLiked",
            field=models.ManyToManyField(
                related_name="user_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
