# Generated by Django 4.2.1 on 2023-10-12 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0025_trendingmessage_viewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="follow",
            field=models.ManyToManyField(
                related_name="follow", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="follow_count",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="following_count",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
