# Generated by Django 4.2.1 on 2023-10-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_profile_follow_profile_follow_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="follow_count",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="following_count",
        ),
    ]
