# Generated by Django 4.2.1 on 2023-10-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_remove_profile_follow_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
