# Generated by Django 4.2.1 on 2024-02-14 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0028_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="follow",
            field=models.ManyToManyField(
                null=True, related_name="follow", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                null=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
