# Generated by Django 4.2.1 on 2024-02-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_alter_profile_bio_alter_profile_follow_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trendingmessage",
            options={"ordering": ["custom_ordering"]},
        ),
        migrations.AddField(
            model_name="trendingmessage",
            name="custom_ordering",
            field=models.FloatField(default=0),
        ),
    ]
