# Generated by Django 4.2.1 on 2024-02-22 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0030_alter_trendingmessage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trendingmessage",
            name="userLiked",
            field=models.ManyToManyField(
                blank=True, related_name="user_like", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="trendingmessage",
            name="viewed",
            field=models.ManyToManyField(
                blank=True, related_name="viewed", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
