# Generated by Django 4.2.1 on 2024-02-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_alter_trendingmessage_userliked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trendingmessage",
            name="hashtags",
            field=models.ManyToManyField(null=True, to="main.hashtag"),
        ),
    ]
