# Generated by Django 4.2.1 on 2024-02-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_alter_trendingmessage_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trendingmessage",
            name="hashtags",
            field=models.ManyToManyField(blank=True, to="main.hashtag"),
        ),
    ]
