# Generated by Django 4.2.1 on 2024-03-07 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0034_reportuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blocked_user",
            field=models.ManyToManyField(
                blank=True, related_name="block_users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="follow",
            field=models.ManyToManyField(
                blank=True, related_name="follow", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
