# Generated by Django 4.2.1 on 2024-03-28 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0035_profile_blocked_user_alter_profile_follow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendingmessage",
            name="option1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trendingmessage",
            name="option2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trendingmessage",
            name="voted",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trendingmessage",
            name="votes_option1",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="trendingmessage",
            name="votes_option2",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
