# Generated by Django 4.2.1 on 2024-03-28 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0038_alter_trendingmessage_voted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trendingmessage",
            name="voted",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
