# Generated by Django 4.2.1 on 2024-03-28 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0040_remove_trendingmessage_option1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendingmessage",
            name="option1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trendingmessage",
            name="option2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trendingmessage",
            name="voted",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trendingmessage",
            name="votes_option1",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="trendingmessage",
            name="votes_option2",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
