# Generated by Django 4.2.1 on 2024-03-29 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0041_trendingmessage_option1_trendingmessage_option2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trendingmessage",
            name="voted",
        ),
        migrations.AddField(
            model_name="trendingmessage",
            name="voted",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="voted", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
