# Generated by Django 4.2.1 on 2024-04-12 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0008_alter_conversationmessage_options"),
        ("main", "0044_notification_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="conversation.conversation",
            ),
        ),
    ]
