# Generated by Django 4.2.1 on 2024-02-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="identify",
            field=models.TextField(null=True),
        ),
    ]
