# Generated by Django 4.2.1 on 2024-02-16 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conversation", "0002_conversation_identify"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="members",
        ),
        migrations.AddField(
            model_name="conversation",
            name="converseUser",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="converseUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="loggeduser",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loggeduser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
