# Generated by Django 4.2.1 on 2024-02-16 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conversation", "0003_remove_conversation_members_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="converseUser",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="identify",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="loggeduser",
        ),
        migrations.AddField(
            model_name="conversation",
            name="members",
            field=models.ManyToManyField(
                related_name="conversations", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
