# Generated by Django 4.2.1 on 2024-02-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0007_alter_conversationmessage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversationmessage",
            options={"ordering": ("created_at",)},
        ),
    ]
